name: Release

on:
  push:
    tags:
      - "[0-9]*.[0-9]*.[0-9]*"

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Install Missing Tools
      run: sudo apt install nasm
    - uses: actions/checkout@v3
      with:
        repository: tianocore/edk2
        ref: 'edk2-stable202205'
        submodules : true
        path: edk2
    - uses: actions/checkout@v3
      with:
        path: edk2/SmokelessRuntimeEFIPatcher
    - name: Build Base Tools
      working-directory: edk2
      run: make -C BaseTools
    - name: Build
      working-directory: edk2
      run: "source edksetup.sh && build -b RELEASE -t GCC5 -p SmokelessRuntimeEFIPatcher/SmokelessRuntimeEFIPatcher.dsc -a X64 -s"
    - name: Pack For Release
      working-directory: edk2/Build/SmokelessRuntimeEFIPatcher/RELEASE_GCC5/X64/
      run: "mkdir -p EFI/BOOT && cp SmokelessRuntimeEFIPatcher.efi  EFI/BOOT/BOOTX64.efi && zip SREP.zip -r EFI/"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: edk2/Build/SmokelessRuntimeEFIPatcher/RELEASE_GCC5/X64/SREP.zip